services:
  - type: web
    name: proxypolitics
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/state
